package pro.pantrypilot.db.classes.session;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;

public class Session {

    private String sessionID;
    private String userID;
    private Timestamp createdAt;
    private Timestamp lastUsed;
    private String ipAddress;

    /**
     * Constructor used for creating a new Session before it is inserted into the database.
     * The sessionID, createdAt, and lastUsed fields will be auto-generated by the database.
     *
     * @param userID The ID of the user who owns this session.
     * @param ipAddress The IP address from which the session was initiated.
     */
    public Session(String userID, String ipAddress) {
        this.userID = userID;
        this.ipAddress = ipAddress;
    }

    /**
     * Constructor that creates a Session object from a ResultSet.
     * This is useful when retrieving session data from the database.
     *
     * @param resultSet The ResultSet obtained from executing a SQL query.
     * @throws SQLException if an error occurs while accessing the ResultSet.
     */
    public Session(ResultSet resultSet) throws SQLException {
        this.sessionID = resultSet.getString("sessionID");
        this.userID = resultSet.getString("userID");
        this.createdAt = resultSet.getTimestamp("createdAt");
        this.lastUsed = resultSet.getTimestamp("lastUsed");
        this.ipAddress = resultSet.getString("ipAddress");
    }

    // Getters and setters

    public String getSessionID() {
        return sessionID;
    }

    public void setSessionID(String sessionID) {
        this.sessionID = sessionID;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getLastUsed() {
        return lastUsed;
    }

    public void setLastUsed(Timestamp lastUsed) {
        this.lastUsed = lastUsed;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
}
